# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20160816_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Athlete',
        ),
    ]
