# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 18:18
from __future__ import unicode_literals

import activities.models
import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0006_auto_20160816_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runMiles', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bikeMiles', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='bike',
            field=models.ForeignKey(blank=True, default=activities.models.Bike(2, 1, 'Fuji Beater', datetime.date(2016, 8, 16), Decimal('0.00'), '', True), null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Bike'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='shoe',
            field=models.ForeignKey(blank=True, default=activities.models.Shoe(1, 1, 'Kinvara 7, green+red', datetime.date(2016, 8, 15), Decimal('31.77'), '', True), null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Shoe'),
        ),
    ]
