# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20160819_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isCyclist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isRunner',
            field=models.BooleanField(default=True),
        ),
    ]
