# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ranToday', models.BooleanField()),
                ('runMiles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('runTime', models.DurationField()),
                ('bikedToday', models.BooleanField()),
                ('bikeMiles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bikeTime', models.DurationField()),
                ('sleepTime', models.DurationField()),
                ('comments', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('firstUseDate', models.DateField()),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('firstUseDate', models.DateField()),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_activity.Bike'),
        ),
        migrations.AddField(
            model_name='activity',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_activity.Shoe'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
