# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='activity',
            name='bikeTime',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='comments',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='activity',
            name='runTime',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sleepTime',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='bike',
            name='firstUseDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bike',
            name='notes',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='firstUseDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='notes',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
