# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_activity', '0003_auto_20160809_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='isDefault',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='isDefault',
            field=models.BooleanField(default=True),
        ),
    ]
