# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_activity', '0005_auto_20160809_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='sleepTime',
        ),
        migrations.AddField(
            model_name='activity',
            name='sleepHours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
