# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_activity', '0006_auto_20160809_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='bikedToday',
            new_name='bikeToday',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='ranToday',
            new_name='runToday',
        ),
    ]
